version: "3"
services:
  server:
    bulid: server
    container_name: qa_district-tasks-server
    ports:
    - 6501:6500
    volumes:
    - server/config.edn:/app/config.edn
    environment:
    - CONFIG=/app/config.edn
    networks:
    - tasks-net
    - qa-net

  ui:
    build: ui
    container_name: qa_district-tasks-ui
    depends_on:
    - server
    ports:
    - 81:80
    volumes:
    - ui/nginx.conf:/etc/nginx/nginx.conf
    - ui/district0x-tasks.io:/etc/nginx/sites-enabled/district0x-tasks.io
    networks:
    - tasks-net
    - qa-net

  networks:
    tasks-net:
      driver: "bridge"