version: "3"
services:

  ganache:
    image: trufflesuite/ganache-cli:v6.7.0
    container_name: dev_ganache
    command:
      --deterministic
      --mnemonic district0x
      --port 8545
      --db /ganache-db
      --noVMErrorsOnRPCResponse
      --gasLimit 70000000
      --allowUnlimitedContractSize
    volumes:
      - /home/$USER/ganache-docker/:/ganache-db
    ports:
      - 8545:8545

  ipfs-daemon:
    image: district0x/ipfs-daemon:latest
    container_name: dev_ipfs-daemon
    volumes:
      - /home/$USER/ipfs-docker:/data/ipfs
    ports:
      - 8080:8080
      - 5001:5001
