version: "3"
services:

  memefactory-server:
    image: district0x/memefactory-server:latest
    container_name: qa_memefactory-server
    depends_on:
      - ipfs-daemon
#      - parity
    networks:
      - memefactory-net
      - ipfs-net
#      - parity-net
    volumes:
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs

  memefactory-api:
    build: memefactory/api
    container_name: qa_memefactory-api
    depends_on:
      - memefactory-server
    ports:
      - 6300:6300
    networks:
      - memefactory-net

  memefactory-ui:
    image: district0x/memefactory-ui:latest
    container_name: qa_memefactory-ui
    depends_on:
     - memefactory-server
     - memefactory-api
     - ipfs-api
     - ipfs-gateway
    ports:
      - 80:80
    networks:
      - ipfs-net

  watchtower:
    image: v2tec/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: watchtower memefactory-server memefactory-ui --interval 30

networks:
  memefactory-net:
    driver: "bridge"
