version: "3"
services:

  memefactory-server:
    image: district0x/memefactory-server:latest
    container_name: qa_memefactory-server
    depends_on:
      - ipfs-daemon
      - parity
    volumes:
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs
    ports:
      - 6300:6300
    networks:
      - memefactory-net
      - ipfs-net
      - parity-net
    labels:
     - "com.centurylinklabs.watchtower.stop-signal=SIGTERM"
     - "com.centurylinklabs.watchtower.enable=true"

  memefactory-ui:
    image: district0x/memefactory-ui:latest
    container_name: qa_memefactory-ui
    depends_on:
     - memefactory-server
     - ipfs-daemon
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=memefactory.qa.district0x.io

networks:
  memefactory-net:
    driver: "bridge"
