version: "3"
services:

  memefactory-server:
    image: district0x/memefactory-server:latest
    container_name: qa_memefactory-server
    depends_on:
      - ipfs-daemon
      - ipfs-server
      - parity
    volumes:
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs
    expose:
      - 6300
    labels:
     - "com.centurylinklabs.watchtower.stop-signal=SIGTERM"
     - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=api.memefactory.qa.district0x.io
      - LETSENCRYPT_HOST=api.memefactory.qa.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io

  memefactory-ui:
    image: district0x/memefactory-ui:latest
    container_name: qa_memefactory-ui
    depends_on:
     - memefactory-server
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=memefactory.qa.district0x.io
      - LETSENCRYPT_HOST=memefactory.qa.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
