version: "3"
services:

  # --- BASE SERVICES ---#

  ipfs-daemon:
    image: district0x/ipfs-daemon:v0.4.21
    container_name: prod_ipfs-daemon
    volumes:
      - /home/$USER/ipfs-docker:/data/ipfs
    networks:
      - ipfs-net
    restart: "on-failure:3"

  ipfs-server:
    image: district0x/ipfs-server:v0.4.21
    container_name: prod_ipfs-server
    links:
      - ipfs-daemon:prod_ipfs-daemon
    depends_on:
      - ipfs-daemon
    networks:
      - ipfs-net
      - default
    volumes:
      - /home/$USER/nginx-docker/cache:/etc/nginx/cache
    environment:
      - VIRTUAL_HOST=ipfs.district0x.io
      - LETSENCRYPT_HOST=ipfs.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=AWS-TLS-1-2-2017-01

  nginx:
    image: jwilder/nginx-proxy:latest
    container_name: prod_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/$USER/nginx-docker/certs:/etc/nginx/certs
      - /home/$USER/nginx-docker/vhost.d:/etc/nginx/vhost.d
      - ./vhost.d/district0x.io:/etc/nginx/vhost.d/district0x.io
      - ./vhost.d/namebazaar.io:/etc/nginx/vhost.d/namebazaar.io
      - ./vhost.d/memefactory.io:/etc/nginx/vhost.d/memefactory.io
      - ./vhost.d/ethlance.com:/etc/nginx/vhost.d/ethlance.com
      - ./vhost.d/contribution.district0x.io:/etc/nginx/vhost.d/contribution.district0x.io
      - ./vhost.d/vote.district0x.io:/etc/nginx/vhost.d/vote.district0x.io
      - ./vhost.d/ipfs.district0x.io:/etc/nginx/vhost.d/ipfs.district0x.io
      - ./vhost.d/ipfs.district0x.io_location:/etc/nginx/vhost.d/ipfs.district0x.io_location
      - /home/$USER/nginx-docker/html:/usr/share/nginx/html
      - /home/$USER/nginx-docker/htpasswd:/etc/nginx/htpasswd
      - /home/$USER/nginx-docker/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    environment:
      - DEFAULT_HOST=prod.district0x.io
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: prod_letsencrypt
    depends_on:
      - nginx
    volumes:
      - /home/$USER/nginx-docker/certs:/etc/nginx/certs
      - /home/$USER/nginx-docker/vhost.d:/etc/nginx/vhost.d
      - /home/$USER/nginx-docker/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # AND
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  watchtower:
    image: v2tec/watchtower:latest
    container_name: prod_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=$SLACK_HOOK_URL
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=Prod-Watchtower-Service
    command: --label-enable --cleanup --interval 300

    # --- CONTRIBUTION PAGE ---#

  district0x-contribution-page:
    image: district0x/contribution-ui:release
    container_name: district0x-contribution-page
    depends_on:
      - nginx
      - letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=contribution.district0x.io
      - LETSENCRYPT_HOST=contribution.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=Mozilla-Modern

  # --- VOTING PAGE ---#

  district0x-voting-page:
    image: district0x/voting-ui:release
    container_name: district0x-voting-page
    depends_on:
      - nginx
      - letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=vote.district0x.io
      - LETSENCRYPT_HOST=vote.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=Mozilla-Modern

  # --- LANDING PAGE ---#

  district0x-landing-page:
    image: district0x/district0x-landing-page:latest
    container_name: district0x-landing-page
    depends_on:
      - nginx
      - letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=district0x.io
      - LETSENCRYPT_HOST=district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=Mozilla-Modern

  # --- NAMEBAZAAR SERVICES ---#

  namebazaar-ui:
    image: district0x/namebazaar-ui:release
    container_name: prod_namebazaar-ui
    depends_on:
     - nginx
     - letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=namebazaar.io
      - LETSENCRYPT_HOST=namebazaar.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=Mozilla-Modern

  # --- ETHLANCE SERVICES ---#

  ethlance-ui:
    image: district0x/ethlance-ui:latest
    container_name: prod_ethlance-ui
    depends_on:
     - nginx
     - letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=ethlance.com
      - LETSENCRYPT_HOST=ethlance.com
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=Mozilla-Modern

  ethlance-emailer:
    image: district0x/ethlance-emailer:latest
    container_name: prod_ethlance-emailer
    volumes:
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - CONFIG=/configs/emailer.config.edn
    restart: "on-failure:3"

  # --- MEMEFACTORY SERVICES ---#

  memefactory-server:
    image: district0x/memefactory-server:release
    container_name: prod_memefactory-server
    depends_on:
      - ipfs-daemon
      - ipfs-server
    volumes:
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs
      - /home/$USER/db:/db
    expose:
      - 6300
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGTERM"
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - CONFIG=/configs/meme.config.prod.edn
      - VIRTUAL_HOST=api.memefactory.io
      - LETSENCRYPT_HOST=api.memefactory.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=AWS-TLS-1-2-2017-01
    restart: "on-failure:3"
    stop_signal: SIGTERM

  memefactory-ui:
    image: district0x/memefactory-ui:release
    container_name: prod_memefactory-ui
    command:
      --enable-middleware-cache
      --disable-ajax-preload
      --disable-ajax-bypass
      --bots-only
    depends_on:
     - memefactory-server
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=memefactory.io
      - LETSENCRYPT_HOST=memefactory.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=Mozilla-Modern
      - PRERENDER_TOKEN=$PRERENDER_TOKEN

  # --- DISTRICT REGISTRY SERVICES ---#

  registry-server:
    image: district0x/registry-server:release
    container_name: prod_registry-server
    depends_on:
      - ipfs-daemon
      - ipfs-server
    volumes:
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs
      - /home/$USER/db:/db
    expose:
      - 6300
    labels:
     - "com.centurylinklabs.watchtower.stop-signal=SIGTERM"
     - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - CONFIG=/configs/registry.config.prod.edn
      - VIRTUAL_HOST=api.registry.district0x.io
      - LETSENCRYPT_HOST=api.registry.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=AWS-TLS-1-2-2017-01
    restart: "on-failure:3"

  registry-ui:
    image: district0x/registry-ui:release
    container_name: prod_registry-ui
    depends_on:
     - registry-server
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=registry.district0x.io
      - LETSENCRYPT_HOST=registry.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=Mozilla-Modern

networks:
  ipfs-net:
    driver: "bridge"
