version: "3"
services:

  memefactory-ui:
    build: memefactory/ui/
    container_name: dev_memefactory-ui
    ports:
      - 3001:80
    volumes:
      - $MEMEFACTORY_DIR/resources/public:/usr/share/nginx/html/build/memefactory

  postgres:
    image: postgres:latest
    container_name: dev_postgres
    volumes:
      - /home/$USER/postgres-docker:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=district0x
      - POSTGRES_DB=district0x
