version: "3"
services:

  # --- BASE SERVICES ---#

  ipfs-daemon:
    image: district0x/ipfs-daemon:v0.4.21
    # container name needs to be ipfs-daemon to be reached on the docker network by the ipfs-server
    container_name: qa_ipfs-daemon
    volumes:
      - /home/$USER/ipfs-docker:/data/ipfs
    networks:
      - ipfs-net
    restart: "on-failure:3"

  ipfs-server:
    image: district0x/ipfs-server:v0.4.21
    container_name: qa_ipfs-server
    links:
      - ipfs-daemon:qa_ipfs-daemon
    depends_on:
      - ipfs-daemon
    networks:
      - ipfs-net
      - default
    volumes:
      - /home/$USER/nginx-docker/cache:/etc/nginx/cache
    environment:
      - VIRTUAL_HOST=ipfs.qa.district0x.io
      - LETSENCRYPT_HOST=ipfs.qa.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=AWS-TLS-1-2-2017-01

  nginx:
    image: jwilder/nginx-proxy:latest
    container_name: qa_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/$USER/nginx-docker/certs:/etc/nginx/certs
      - /home/$USER/nginx-docker/vhost.d:/etc/nginx/vhost.d
      - ./vhost.d/memefactory.qa.district0x.io:/etc/nginx/vhost.d/memefactory.qa.district0x.io
      - ./vhost.d/registry.qa.district0x.io:/etc/nginx/vhost.d/registry.qa.district0x.io
      - ./vhost.d/ipfs.qa.district0x.io:/etc/nginx/vhost.d/ipfs.qa.district0x.io
      - ./vhost.d/ipfs.qa.district0x.io_location:/etc/nginx/vhost.d/ipfs.qa.district0x.io_location
      - ./htpasswd:/etc/nginx/htpasswd
      - /home/$USER/nginx-docker/html:/usr/share/nginx/html
      - /home/$USER/nginx-docker/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    environment:
      - DEFAULT_HOST=qa.district0x.io
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12-rc.1
    container_name: qa_letsencrypt
    depends_on:
      - nginx
    volumes:
      - /home/$USER/nginx-docker/certs:/etc/nginx/certs
      - /home/$USER/nginx-docker/vhost.d:/etc/nginx/vhost.d
      - /home/$USER/nginx-docker/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # AND
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  watchtower:
    image: v2tec/watchtower:latest
    container_name: qa_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=$SLACK_HOOK_URL
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=QA-Watchtower-Service
    command: --label-enable --cleanup --interval 300

  # --- MEMEFACTORY SERVICES ---#

  memefactory-server:
    image: district0x/memefactory-server:latest
    container_name: qa_memefactory-server
    depends_on:
      - ipfs-daemon
      - ipfs-server
    volumes:
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs
      - /home/$USER/db:/db
    expose:
      - 6300
    labels:
     - "com.centurylinklabs.watchtower.stop-signal=SIGTERM"
     - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - CONFIG=/configs/meme.config.qa.edn
      - VIRTUAL_HOST=api.memefactory.qa.district0x.io
      - LETSENCRYPT_HOST=api.memefactory.qa.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=AWS-TLS-1-2-2017-01
    restart: "on-failure:3"
    stop_signal: SIGTERM

  memefactory-ui:
    image: district0x/memefactory-ui:latest
    container_name: qa_memefactory-ui
    command:
      --enable-middleware-cache
      --disable-ajax-preload
      --disable-ajax-bypass
      --bots-only
    depends_on:
     - memefactory-server
    volumes:
      - /home/$USER/configs/_redirects:/app/_redirects
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=memefactory.qa.district0x.io
      - LETSENCRYPT_HOST=memefactory.qa.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=Mozilla-Modern
      - PRERENDER_TOKEN=$PRERENDER_TOKEN
      - DEBUG=prerendercloud

  # --- DISTRICT REGISTRY SERVICES ---#

  registry-server:
    image: district0x/registry-server:latest
    container_name: qa_registry-server
    depends_on:
      - ipfs-daemon
      - ipfs-server
      # - rinkeby
    volumes:
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs
      - /home/$USER/db:/db
    expose:
      - 6300
    labels:
     - "com.centurylinklabs.watchtower.stop-signal=SIGTERM"
     - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - CONFIG=/configs/registry.config.qa.edn
      - VIRTUAL_HOST=api.registry.qa.district0x.io
      - LETSENCRYPT_HOST=api.registry.qa.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=AWS-TLS-1-2-2017-01
    restart: "on-failure:3"

  registry-ui:
    image: district0x/registry-ui:latest
    container_name: qa_registry-ui
    depends_on:
     - registry-server
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=registry.qa.district0x.io
      - LETSENCRYPT_HOST=registry.qa.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - SSL_POLICY=Mozilla-Modern

networks:
  ipfs-net:
    driver: "bridge"
