version: "3"
services:

  parity:
    image: parity/parity:v2.3.8
    container_name: qa_parity
    command:
      --chain ropsten
      --base-path /home/parity/.local/share/io.parity.ethereum/
      --jsonrpc-apis 'web3,eth,net,parity,personal'
      --jsonrpc-interface '0.0.0.0'
      --jsonrpc-hosts none
      --jsonrpc-cors '*'
      --cache-size 6000
      --db-compaction ssd
      --mode active
      --pruning fast
      --logging info
      --geth
      --jsonrpc-port 8545
    ports:
      - 8545:8545      
    volumes:
      - /home/$USER/parity-docker/:/home/parity/.local/share/io.parity.ethereum/
    # networks:
    #   - parity-net
    environment:
      - VIRTUAL_PORT=8545
      - VIRTUAL_HOST=ropsten.district0x.io
    
  ipfs-daemon:
    build: ipfs/daemon
    container_name: qa_ipfs-daemon
    volumes:
      - /home/$USER/ipfs-docker:/data/ipfs
    networks:
      - ipfs-net

  ipfs-server:
    build: ipfs/server
    container_name: qa_ipfs-server
    depends_on:
      - ipfs-daemon
    networks:
      - ipfs-net
      - default
    environment:
      - VIRTUAL_HOST=ipfs.qa.district0x.io
       
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  watchtower:
    image: v2tec/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/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
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=QA-Watchtower-Service
    command: --label-enable --cleanup --interval 300

networks:
  ipfs-net:
    driver: "bridge"
  # parity-net:
  #   driver: "bridge"
