version: "3"
services:

  # --- BASE SERVICES ---#

  rinkeby:
    image: ethereum/client-go:stable
    container_name: rinkeby_geth
    command:
      --rinkeby
      --rpc
      --rpcapi db,eth,net,web3
      --rpcaddr "0.0.0.0"
      --cache=6000
      --rpcport 8545
      --rpccorsdomain "*"
    volumes:
      - /home/$USER/rinkeby-docker/:/root/.ethereum
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_PORT=8545
      - VIRTUAL_HOST=rinkeby.district0x.io
      - LETSENCRYPT_HOST=rinkeby.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
    restart: always

  ropsten:
    image: parity/parity:stable
    container_name: ropsten_parity
    command:
      --chain ropsten
      --base-path /home/parity/.local/share/io.parity.ethereum/
      --jsonrpc-apis 'web3,eth,net,parity'
      --jsonrpc-interface '0.0.0.0'
      --jsonrpc-hosts none
      --jsonrpc-cors '*'
      --cache-size 6000
      --db-compaction ssd
      --mode active
      --pruning fast
      --logging info
      --geth
      --jsonrpc-port 8545
    volumes:
      - /home/$USER/parity-docker/:/home/parity/.local/share/io.parity.ethereum/
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_PORT=8545
      - VIRTUAL_HOST=ropsten.district0x.io
      - LETSENCRYPT_HOST=ropsten.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
    restart: always

  ipfs-daemon:
    image: district0x/ipfs-daemon:latest
    container_name: qa_ipfs-daemon
    volumes:
      - /home/$USER/ipfs-docker:/data/ipfs
    networks:
      - ipfs-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  ipfs-server:
    image: district0x/ipfs-server:latest
    container_name: qa_ipfs-server
    depends_on:
      - ipfs-daemon
    networks:
      - ipfs-net
      - default
    volumes:
      - /home/$USER/nginx-docker/cache:/etc/nginx/cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=ipfs.qa.district0x.io
      - LETSENCRYPT_HOST=ipfs.qa.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io

  nginx:
    image: jwilder/nginx-proxy:latest
    container_name: qa_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/$USER/nginx-docker/certs:/etc/nginx/certs
      - /home/$USER/nginx-docker/vhost.d:/etc/nginx/vhost.d
      - /home/$USER/nginx-docker/html:/usr/share/nginx/html
      - /home/$USER/nginx-docker/htpasswd:/etc/nginx/htpasswd
      - /home/$USER/nginx-docker/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    environment:
      - DEFAULT_HOST=qa.district0x.io
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: qa_letsencrypt
    depends_on:
      - nginx
    volumes:
      - /home/$USER/nginx-docker/certs:/etc/nginx/certs
      - /home/$USER/nginx-docker/vhost.d:/etc/nginx/vhost.d
      - /home/$USER/nginx-docker/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # AND
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  watchtower:
    image: v2tec/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/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
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=QA-Watchtower-Service
    command: --label-enable --cleanup --interval 300

  # --- MEMEFACTORY SERVICES ---#

  memefactory-server:
    image: district0x/memefactory-server:latest
    container_name: qa_memefactory-server
    depends_on:
      - ipfs-daemon
      - ipfs-server
      - parity
    volumes:
      - /home/$USER/logs:/logs
      - /home/$USER/configs:/configs
      - /home/$USER/db:/db
    expose:
      - 6300
    labels:
     - "com.centurylinklabs.watchtower.stop-signal=SIGTERM"
     - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - CONFIG=/configs/meme.config.qa.edn
      - VIRTUAL_HOST=api.memefactory.qa.district0x.io
      - LETSENCRYPT_HOST=api.memefactory.qa.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
    restart: on-failure

  memefactory-ui:
    image: district0x/memefactory-ui:latest
    container_name: qa_memefactory-ui
    command:
#      --enable-middleware-cache
#      --disable-ajax-preload
#      --disable-ajax-bypass
      --bots-only
    depends_on:
     - memefactory-server
    volumes:
      - /home/$USER/configs/_redirects:/app/_redirects
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=memefactory.qa.district0x.io
      - LETSENCRYPT_HOST=memefactory.qa.district0x.io
      - LETSENCRYPT_EMAIL=filip@district0x.io
      - PRERENDER_TOKEN=$PRERENDER_TOKEN
      - DEBUG=prerendercloud

networks:
  ipfs-net:
    driver: "bridge"
