version: "3"
services:

#   parity:
#     image: parity/parity:v2.0.6
#     container_name: qa_parity
#     command:
#       --chain ropsten
#       --base-path /home/parity/.local/share/io.parity.ethereum/
#       --jsonrpc-apis 'web3,eth,net,parity,personal'
#       --jsonrpc-interface all
#       --jsonrpc-hosts all
#       --jsonrpc-cors '*'
#       --cache-size 6000
#       --db-compaction ssd
#       --mode active
#       --pruning fast
#       --logging info
#       --warp
#       --snapshot-peers 15
#       --jsonrpc-port 8545
#     volumes:
# #      - /home/$USER/parity-docker/testnet:/home/parity/.local/share/io.parity.ethereum/
#       - /home/$USER/.local/share/io.parity.ethereum/:/home/parity/.local/share/io.parity.ethereum/
#     networks:
#       - parity-net
#   ropsten:
#     build: ropsten
#     container_name: qa_ropsten
#     depends_on:
#       - parity
#     ports:
#       - 8545:8545
#     networks:
#       - parity-net

  ipfs-daemon:
    build: ipfs/daemon
    container_name: qa_ipfs-daemon
    volumes:
      - /home/$USER/ipfs-docker:/data/ipfs
      - /home/$USER/ipfs-docker-staging:/export
    networks:
      - ipfs-net

  ipfs-api:
    build: ipfs/api
    container_name: qa_ipfs-api
    depends_on:
      - ipfs-daemon
    ports:
      - 5001:5001
    networks:
      - ipfs-net

  ipfs-gateway:
    build: ipfs/gateway
    container_name: qa_ipfs-gateway
    depends_on:
      - ipfs-daemon
    ports:
      - 8080:8080
    networks:
      - ipfs-net

  watchtower:
    image: v2tec/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/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
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=QA-Watchtower-Service
    command: --label-enable --cleanup --interval 300

networks:
  ipfs-net:
    driver: "bridge"
  # parity-net:
  #   driver: "bridge"
