version: "3"
services:

  parity:
    image: parity/parity:stable
    container_name: qa_parity
    ports:
      - 8545:8545
      # - "8180:8180"
      # - "8546:8546"
      # - "30303:30303"
      # - "30303:30303/udp"
    volumes:
      - /tmp/parity-docker/testnet:/home/parity/.local/share/io.parity.ethereum/
    networks:
      - memefactory-net
    command:
      --chain ropsten
      --base-path /home/parity/.local/share/io.parity.ethereum/
      --jsonrpc-apis 'web3,eth,net,parity,personal'
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-cors '*'
      --cache-size 1024
      --db-compaction ssd
      --mode active
      --jsonrpc-port 8545

  ipfs:
    build: builds/ipfs
    container_name: qa_ipfs
    ports:
      - 8080:8080
      - 4001:4001
      - 127.0.0.1:5001:5001
    volumes:
      - /home/$USER/.ipfs/keystore/:/data/ipfs/keystore/
    networks:
      - memefactory-net

  server:
    build: builds/server
    container_name: qa_memefactory-server
    depends_on:
      - ipfs
      - parity
    ports:
      - 6300:6300
    networks:
      - memefactory-net

  ui:
    build: builds/ui
    container_name: qa_memefactory-ui
    depends_on:
     - ipfs
     - parity
     - server
    ports:
      - 80:80
    networks:
      - memefactory-net

networks:
  memefactory-net:
    driver: "bridge"
